export {
  defineComponent,
  defineEvent,
  WorldInstance,
  EntityInstance,
  EventBus,
  getComponentId,
  type ComponentDef,
  type EventDef,
  type QueryFilter,
  type SystemCallback,
} from './core';

export {
  World,
  Entity,
  Component,
  Behavior,
  useWorld,
  useEntity,
  useSystem,
  useQuery,
  useFacet,
  useSpawn,
  useEvent,
  useEventListener,
  useEntityLifecycle,
  useComponentLifecycle,
  type SpawnDescriptor,
} from './react';
